This workshop is designed for application developers, data engineers, and architects who are responsible for building data pipelines for use-cases such as: data ingest, real-time analytics and data import/export in a Cloud environment. Through hands-on labs, the course explores installation and orchestration of Spring Cloud Data Flow as well as creating, configuring and deploying Streams microservice applications and Tasks (ephemeral microservices). This workshop also includes the development of custom Spring Boot applications using Spring Cloud Stream.

== Topics:
* Introduction to Spring Cloud Data Flow
* Installation and Orchestration
* Architecture Overview 
* Create and deploy Streams
* Create and launch Tasks 
* Create custom Spring Cloud Streams applications

== Pre-requisites

* Java development skills, including ability to run Apache Maven commands
* Familiarity with running basic OS commands from a shell/command-prompt
* Technical Requirements
* JDK 8 or later installed
* Apache Maven installed
* Ability to retrieve class materials via:
   * github.com 
   * thumb drive
